version: '3.8'

services:
  phishguard-ml:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phishguard-ml-api
    ports:
      - "8000:8000"
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount models directory (optional, for model updates)
      - ./models:/app/models:ro
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - phishguard-network

networks:
  phishguard-network:
    driver: bridge
